// Generated by https://quicktype.io

export interface User {
    name:     string;
    dni:      string;
    number:   string;
    email:    string;
    birthday: string;
    numberOfReservations?: number;
}
